# Project information
site_name: Documentation Otletosphère
site_url: 'https://hyperotlet.github.io/otletosphere/'
repo_name: 'hyperotlet/otletosphere'
repo_url: 'https://github.com/hyperotlet/otletosphere'
edit_uri: ''
site_description: Documentation du projet Otletosphère
copyright: '© HyperOtlet 2020'

# Navigation
nav:
  - Accueil: index.md
  - Démarche:
    - Choix techniques: demarche/choix-technique.md
    - Multilingue: demarche/multilingue.md
    - Structure des données: demarche/structure-donnees.md
  - Guide utilisation:
    - Éléments d'interface: utilisation/elements-interface.md
    - Naviguer dans le réseau: utilisation/navigation-reseau.md
    - Sélectionner une entité: utilisation/selection-entites.md
    - Trier les entités: utilisation/trier-entites.md
  - FAQ: faq.md
  - Historique: historique-versions.md 
  - Développement:
    - Architecture:
      - Code source: developpement/architecture-code-source.md
      - Bibliothèques: developpement/bibliotheques.md
    - Téléchargement et installation: developpement/installation.md
    - Inscrire données: developpement/inscrire-donnees.md
    - Modifier code source:
      - Outils développement: modifier_code/outils-developpement.md
      - Modifier groupes: modifier_code/modifier-groupes.md
      - Modifier volet: modifier_code/modifier-volet.md
      - Modifier traduction: modifier_code/modifier-traduction.md
    

# Theme configuration
theme:
  name: material
  language: fr
  palette:
    primary: indigo
    accent: indigo
  font: false
extra_css:
  - extras/style.css
extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - meta
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.tilde

# plugins
plugins:
  - search:
      lang:
        - fr